Repository neo4j-contrib/cypher-dsl, pull requests merged in 2021-03, with the labels that each got.

#159 Fix missing labels for nodes after `WITH`.
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/DefaultVisitor.java
  neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
Labels: type: bug

#158 improve pretty printing for subqueries
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/renderer/PrettyPrintingVisitor.java
  neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
Labels: type: improvement

#160 GH-157 - Provide a method to turn a Java map into an expression.
  neo4j-cypher-dsl-examples/src/test/java/org/neo4j/cypherdsl/examples/core/PropertiesTest.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ExposesProperties.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/MapExpression.java
  neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/CypherIT.java
Labels: type: new-feature

#162 GH-155 - Provide infrastructure for generating a static meta model.
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/pom.xml
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/AbstractClassNameGenerator.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/AbstractModelBuilder.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/ClassNameGenerator.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/Configuration.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/FieldNameGenerator.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/ModelBuilder.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/NodeImplBuilder.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/NodeModelBuilder.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/NodeNameGenerator.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/PropertyDefinition.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/RelationshipImplBuilder.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/RelationshipModelBuilder.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/RelationshipNameGenerator.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/main/java/org/neo4j/cypherdsl/codegen/core/RelationshipPropertyDefinition.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/test/java/org/neo4j/cypherdsl/codegen/core/ConstantFieldNamingStrategyTest.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/test/java/org/neo4j/cypherdsl/codegen/core/NodeNameGeneratorTest.java
  neo4j-cypher-dsl-codegen/neo4j-cypher-dsl-codegen-core/src/test/java/org/neo4j/cypherdsl/codegen/core/RelationshipNameGeneratorTest.java
  neo4j-cypher-dsl-codegen/pom.xml
  pom.xml
Labels: type: new-feature

#167 Add support for some Query-DSL expressions.
  docs/appendix/index.adoc
  docs/appendix/query-dsl-support.adoc
  neo4j-cypher-dsl/pom.xml
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/Cypher.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/ForeignAdapter.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/QueryDSLAdapter.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/querydsl/CypherContext.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/querydsl/CypherTemplates.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/querydsl/ToCypherFormatStringVisitor.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/querydsl/UnsupportedOperatorException.java
  neo4j-cypher-dsl/src/main/java/org/neo4j/cypherdsl/core/querydsl/package-info.java
  neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/querydsl/Person.java
  neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/querydsl/Place.java
  neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/querydsl/QueryDSLAdapterTest.java
  neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/querydsl/Stuff.java
  pom.xml
Labels: type: new-feature
